GET http://localhost:3001/api

########

GET http://localhost:3001/api/mascotas


########


GET http://localhost:3001/api/mascotas/1



##########

GET http://localhost:3001/api/mascotas/6


#########

GET https://examen-backend-ivangarcia.onrender.com/api/mascotas